sudo: required
dist: trusty
group: edge

language: java

jdk:
  - oraclejdk8
  - oraclejdk11

script: ./mvnw install

cache:
  directories:
  - ~/.m2/repository
  - ~/.m2/wrapper
  
before_cache:
  - rm -Rf ~/.m2/repository/com/devskiller/jpa2ddl/